; SPRITES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : SpriteTiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "SpriteTiles", rom0

; Start of tile array.
Sprites::
DB $3F,$FF,$3F,$FF,$FF,$C0,$FC,$C3
DB $FF,$C3,$FF,$C3,$FF,$C0,$FF,$C0
DB $FF,$C0,$FF,$C3,$FF,$C3,$FF,$C0
DB $FF,$C0,$FF,$C0,$3F,$FF,$3F,$FF
DB $FC,$FF,$FC,$FF,$FF,$03,$CF,$33
DB $FF,$33,$FF,$33,$FF,$03,$FF,$03
DB $FF,$03,$FF,$F3,$FF,$F3,$FF,$03
DB $FF,$03,$FF,$03,$FC,$FF,$FC,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$7E,$FF,$81,$FF,$81,$FF,$83
DB $FF,$85,$FF,$89,$FF,$91,$FF,$A1
DB $FF,$C1,$FF,$81,$FF,$81,$FF,$7E
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$08,$FF,$18,$FF,$28,$FF,$48
DB $FF,$08,$FF,$08,$FF,$08,$FF,$08
DB $FF,$08,$FF,$08,$FF,$08,$FF,$7F
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$7E,$FF,$81,$FF,$01,$FF,$01
DB $FF,$01,$FF,$02,$FF,$04,$FF,$08
DB $FF,$10,$FF,$20,$FF,$40,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$7E,$FF,$81,$FF,$01,$FF,$01
DB $FF,$01,$FF,$01,$FF,$3E,$FF,$01
DB $FF,$01,$FF,$01,$FF,$81,$FF,$7E
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$82,$FF,$82,$FF,$82,$FF,$82
DB $FF,$82,$FF,$FF,$FF,$02,$FF,$02
DB $FF,$02,$FF,$02,$FF,$02,$FF,$02
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$FF,$80,$FF,$80,$FF,$80
DB $FF,$80,$FF,$80,$FF,$FE,$FF,$01
DB $FF,$01,$FF,$01,$FF,$81,$FF,$7E
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$3C,$FF,$42,$FF,$80,$FF,$80
DB $FF,$80,$FF,$BE,$FF,$C1,$FF,$81
DB $FF,$81,$FF,$81,$FF,$81,$FF,$7E
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$FF,$01,$FF,$01,$FF,$02
DB $FF,$02,$FF,$02,$FF,$04,$FF,$04
DB $FF,$04,$FF,$08,$FF,$08,$FF,$08
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$7E,$FF,$81,$FF,$81,$FF,$81
DB $FF,$81,$FF,$81,$FF,$7E,$FF,$81
DB $FF,$81,$FF,$81,$FF,$81,$FF,$7E
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$7E,$FF,$81,$FF,$81,$FF,$81
DB $FF,$81,$FF,$81,$FF,$83,$FF,$7D
DB $FF,$01,$FF,$01,$FF,$81,$FF,$7E
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$31,$FF,$49,$FF,$4A,$FF,$34
DB $FF,$04,$FF,$08,$FF,$10,$FF,$20
DB $FF,$2C,$FF,$52,$FF,$92,$FF,$8C
SpritesEnd::

; End of SPRITES.Z80
