; TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : BGTiles
;   Bank                 : 2
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "BGTiles", rom0

; Start of tile array.
Tiles::
        ; Start of tile array.
        DB $00,$00,$00,$00,$00,$00,$00,$00
        DB $00,$00,$00,$00,$00,$00,$00,$00

        ; Start of tile array.
        DB $14,$00,$00,$08,$14,$00,$00,$14
        DB $14,$00,$00,$08,$14,$00,$00,$14

        ; Start of tile array.
        DB $04,$00,$8E,$04,$DB,$8E,$75,$DB
        DB $AE,$73,$DD,$36,$EB,$1C,$FF,$00

        ; Start of tile array.
        DB $40,$00,$F0,$40,$A9,$F0,$5F,$B1
        DB $EE,$1B,$FD,$26,$FF,$50,$FF,$88

        ; Start of tile array.
        DB $C0,$3F,$C0,$3F,$00,$C0,$00,$C0
        DB $00,$C0,$00,$C0,$3F,$C0,$3F,$C0

        ; Start of tile array.
        DB $06,$C0,$06,$C0,$06,$C0,$06,$C0
        DB $3F,$C0,$3F,$C0,$C0,$3F,$C0,$3F

        ; Start of tile array.
        DB $03,$FC,$03,$FC,$60,$03,$60,$03
        DB $60,$03,$60,$03,$FC,$03,$FC,$03

        ; Start of tile array.
        DB $00,$03,$00,$03,$00,$03,$00,$03
        DB $FC,$03,$FC,$03,$03,$FC,$03,$FC

        ; Start of tile array.
        DB $03,$01,$07,$03,$0E,$07,$1C,$0F
        DB $39,$1E,$73,$3C,$E6,$78,$CC,$F0

        ; Start of tile array.
        DB $C0,$80,$E0,$C0,$70,$E0,$38,$F0
        DB $9C,$78,$CE,$3C,$67,$1E,$33,$0F

        ; Start of tile array.
        DB $00,$00,$00,$00,$00,$00,$00,$00
        DB $00,$00,$00,$00,$00,$00,$3F,$7F

        ; Start of tile array.
        DB $00,$00,$00,$00,$00,$00,$00,$00
        DB $00,$00,$00,$00,$00,$00,$FC,$FE

        ; Start of tile array.
        DB $00,$00,$01,$01,$01,$03,$07,$03
        DB $02,$07,$0E,$07,$04,$0F,$1C,$0F

        ; Start of tile array.
        DB $08,$1F,$38,$1F,$10,$3F,$71,$3E
        DB $23,$7C,$E7,$78,$C6,$F8,$8C,$F0

        ; Start of tile array.
        DB $80,$00,$80,$80,$80,$C0,$C0,$C0
        DB $60,$C0,$70,$E0,$20,$F0,$30,$F0

        ; Start of tile array.
        DB $10,$F0,$18,$F8,$08,$F8,$8C,$7C
        DB $C4,$3E,$E6,$1F,$63,$1F,$31,$0F

        ; Start of tile array.
        DB $C0,$3F,$C0,$3F,$03,$C0,$03,$C0
        DB $3F,$C0,$3F,$C0,$C0,$3F,$C0,$3F

        ; Start of tile array.
        DB $03,$FC,$03,$FC,$00,$03,$00,$03
        DB $FC,$03,$FC,$03,$03,$FC,$03,$FC

        ; Start of tile array.
        DB $FF,$7F,$FF,$FF,$FF,$FF,$FF,$FF
        DB $3F,$C0,$3F,$C0,$C0,$3F,$C0,$3F

        ; Start of tile array.
        DB $FF,$FE,$FF,$FF,$FF,$FF,$FF,$FF
        DB $FC,$03,$FC,$03,$03,$FC,$03,$FC

        ; Start of tile array.
        DB $FF,$7F,$FF,$FF,$FF,$FF,$FF,$FF
        DB $00,$C0,$00,$C0,$3F,$C0,$3F,$C0

        ; Start of tile array.
        DB $FF,$FE,$FF,$FF,$FF,$FF,$FF,$FF
        DB $60,$03,$60,$03,$FC,$03,$FC,$03

        ; Start of tile array.
        DB $3C,$3C,$42,$42,$81,$81,$99,$99
        DB $99,$99,$81,$81,$42,$42,$3C,$3C

        ; Start of tile array.
        DB $33,$0F,$67,$1E,$CE,$3C,$9C,$78
        DB $38,$F0,$70,$E0,$E0,$C0,$C0,$80

        ; Start of tile array.
        DB $CC,$F0,$E6,$78,$73,$3C,$39,$1E
        DB $1C,$0F,$0E,$07,$07,$03,$03,$01

        ; Start of tile array.
        DB $03,$01,$07,$03,$0E,$07,$1C,$0F
        DB $39,$1E,$73,$3C,$E6,$78,$CC,$F0

        ; Start of tile array.
        DB $C0,$80,$E0,$C0,$70,$E0,$38,$F0
        DB $9C,$78,$CE,$3C,$67,$1E,$33,$0F

        ; Start of tile array.
        DB $33,$0F,$67,$1E,$CE,$3C,$9C,$78
        DB $38,$F0,$70,$E0,$E0,$C0,$C0,$80

        ; Start of tile array.
        DB $CC,$F0,$E6,$78,$73,$3C,$39,$1E
        DB $1C,$0F,$0E,$07,$07,$03,$03,$01

        ; End of TILES.Z80

        
TilesEnd::

; End of TILES.Z80
